apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-pvc
  labels:
    app.kubernetes.io/name: grocy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
