apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller  # <-- Coincide con los labels abajo
  template:
    metadata:
      labels:
        app: unifi-controller  # <-- Debe coincidir con matchLabels
    spec:
      nodeSelector:
        kubernetes.io/hostname: gandalfgrid02  # <-- Indentación corregida
      volumes:
        - name: unifi-storage
          persistentVolumeClaim:
            claimName: unifi
      containers:
        - name: unifi-controller
          image: jacobalberty/unifi:v9.0
          ports:
            - containerPort: 3478
              protocol: UDP 
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8843
              protocol: TCP
            - containerPort: 8880
              protocol: TCP
            - containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: unifi-storage
              mountPath: /unifi
              subPath: unifi
