apiVersion: v1
kind: Service
metadata:
  name: unifi-controllerlb
  namespace: unifi
spec:
  selector:
    app: unifi-controller
  ports:
    - name: unifi-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: web-interface
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
