apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-pvc
  labels:
    app.kubernetes.io/name: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
