kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: "admin" # temporal
    envFromSecret: grafana-authentik

    grafana.ini:
      server:
        root_url: "https://grafana.sanvicr.com"

      auth.generic_oauth:
        tls_skip_verify_insecure: true
        enabled: true
        name: "Authentik"
        allow_sign_up: true
        auto_login: false
        client_id: "TUhpWEAr4cKjSjpMVsNnHNHl9PHRKEpcjjkfsdQs"
        client_secret: "$__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
        scopes: "openid profile email"
        auth_url: "https://authentik.int.sanvicr.com:9443/application/o/authorize/"
        token_url: "https://authentik.int.sanvicr.com:9443/application/o/token/"
        api_url: "https://authentik.int.sanvicr.com:9443/application/o/userinfo/"
        use_pkce: true

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - grafana.sanvicr.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.sanvicr.com

  prometheus:
    enabled: true
    prometheusSpec:
      replicas: 1
      retention: 7d
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 2Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
      enableAdminAPI: false

  alertmanager:
    enabled: true
    alertmanagerSpec:
      replicas: 1
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true

  prometheusOperator:
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 500Mi

  kubeEtcd:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubelet:
    enabled: true

  defaultRules:
    create: true