configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 172.20.1.18-172.20.1.22
controller:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi
