replicaCount: 1

image:
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi




service:
  type: ClusterIP
  port: 9116

serviceMonitor:
  enabled: true
  path: /snmp
  interval: 15s
  scrapeTimeout: 10s

  # Default module/auth para los targets
  module:
    - if_mib
  auth:
    - public_v2

  labels:
    release: monitoring-app-of-apps

  # Un ServiceMonitor target por equipo
  params:
    - name: fortigate
      target: 172.20.1.17
      module:
        - if_mib
      auth:
        - public_v2
      labels:
        device: fortigate
        vendor: fortinet
        site: homelab
        release: monitoring-app-of-apps

    - name: pfsense
      target: 10.48.0.2
      module:
        - if_mib
      auth:
        - public_v2
      labels:
        device: pfsense
        vendor: netgate
        site: sanvicente
        release: monitoring-app-of-apps

    - name: core-switch-sanvicente
      target: 192.168.1.10
      module:
        - if_mib
      auth:
        - public_v2
      labels:
        device: core-switch-sanvicente
        vendor: unifi
        site: sanvicente
        release: monitoring-app-of-apps

 
  relabelings: []
  additionalMetricsRelabels: {}
  additionalMetricsRelabelConfigs: []

  selfMonitor:
    enabled: true
    interval: 60s
    scrapeTimeout: 30s
    labels:
      release: monitoring-app-of-apps