apiVersion: v1
kind: Service
metadata:
  name: proximo-mcp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: proximo-mcp
  ports:
    - name: http
      port: 41243
      targetPort: http
      protocol: TCP
