apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
spec:
  project: default
  source:
    repoURL: 'https://github.com/svargas-sre/sanvicr-gitops.git'
    targetRevision: HEAD
    path: apps/minecraft  # Minecraft manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
