apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
spec:
  project: default
  source:
    repoURL: 'https://github.com/svargas-sre/sanvicr-gitops.git'
    targetRevision: HEAD
    path: apps/unifi  # Unifi manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
