apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/svargas-sre/sanvicr-gitops.git
    targetRevision: HEAD
    path: apps/actual-budget
  destination:
    server: https://kubernetes.default.svc
    namespace: actual-budget
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
