apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proximo-mcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/svargas-sre/sanvicr-gitops.git
    targetRevision: main
    path: apps/proximo-mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
