apiVersion: v1
kind: Service
metadata:
  name: minecraft-metrics-lb
  annotations:
    metallb.io/address-pool: services-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 172.20.50.121
  selector:
    app: minecraft
    instance: mc-2
  ports:
    - name: minecraft
      protocol: TCP
      port: 8000
      targetPort: 8000
  
